blank_issues_enabled: false
contact_links:
  - name: "‚ùì Question"
    url: https://github.com/torchbox/django-pattern-library/discussions
    about: Use GitHub Discussions to get help with this project.
